version: "3.8"

services:

  db:
    image: postgis/postgis:15-3.3
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
    volumes:
      - $HOME/docker/volumes/postgres:/var/lib/postgresql/data
    ports:
      - 5432:5432
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5

  migration:
    build: ./
    command: [bash, -c, "alembic upgrade head"]
    volumes:
      - ./:/root/app
    working_dir: /root/app
    environment:
      - POSTGRES_SERVER=db:5432
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=postgres
    links:
      - db
    depends_on:
      db:
        condition: service_healthy

  service:
    build: ./
    environment:
      - PROJECT_NAME=strava
      - POSTGRES_SERVER=db:5432
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=postgres
    ports:
      - 8080:8080
    volumes:
      - ./:/app
    depends_on:
      - migration

