services:
  db:
    image: postgis/postgis:17-3.5
    network_mode: host
    command: ["postgres", "-p", "5432"]
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
    volumes:
      - $HOME/docker/volumes/postgres:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -p 5432"]
      interval: 5s
      timeout: 5s
      retries: 5

  migration:
    build:
      context: .
      dockerfile: Dockerfile
      network: host
    network_mode: host
    command: [alembic, upgrade, head]
    volumes:
      - ./:/app
    working_dir: /app
    environment:
      - PROJECT_NAME=strava
      - ENVIRONMENT=development
      - LOGFIRE_TOKEN=${LOGFIRE_TOKEN}
      - POSTGRES_SERVER=localhost:5432
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=postgres
    depends_on:
      db:
        condition: service_healthy

  service:
    build:
      context: .
      dockerfile: Dockerfile
      network: host
    network_mode: host
    command:
      - python
      - "-m"
      - uvicorn
      - "strava.main:app"
      - "--host"
      - "0.0.0.0"
      - "--port"
      - "8080"
      - "--reload"
    environment:
      - PROJECT_NAME=strava
      - ENVIRONMENT=development
      - LOGFIRE_TOKEN=${LOGFIRE_TOKEN}
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - POSTGRES_SERVER=localhost:5432
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=postgres
    volumes:
      - ./:/app
    depends_on:
      migration:
        condition: service_completed_successfully
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:8080/ready || exit 1"]
      interval: 10s
      timeout: 10s
      retries: 5
