[project]
name = "strava"
version = "0.1.0"
description = "A strava clone service for storing running, hiking and ski routes"
readme = "README.md"
license = "MIT"
requires-python = ">=3.11"
authors = [
  { name = "martinabeleda", email = "martin.abeleda@gmail.com" },
]
dependencies = [
  "uvicorn",
  "fastapi>=0.100.0",
  "pydantic>=2.0.0",
  "pydantic-settings",
  "geojson-pydantic",
  "shapely",
  "sqlalchemy>=2.0.0",
  "geoalchemy2",
  "alembic",
  "psycopg2-binary",
]

[dependency-groups]
dev = [
  "pytest>=7.2.0",
  "pytest-cov>=4.0.0",
  "pre-commit",
  "black>=23.7.0",
  "isort>=5.12.0",
  "ruff>=0.0.280",
  "httpx>=0.23.0",
]

[build-system]
requires = ["hatchling>=1.0.0"]
build-backend = "hatchling.build"

[tool.isort]
profile = "black"
multi_line_output = 3
line_length = 120
use_parentheses = true
known_first_party = "strava"

[tool.black]
max-line-length = 100
line-length = 100
