[tool.poetry]
name = "strava"
version = "0.1.0"
description = "A strava clone service for storing running, hiking and ski routes"
authors = ["martinabeleda <martin.abeleda@gmail.com>"]
license = "MIT"

[tool.poetry.dependencies]
python = "^3.9"
fastapi = "^0.87.0"
geojson-pydantic = "^0.4.3"
alembic = "^1.8.1"
shapely = "^1.8.5"
uvicorn = "^0.19.0"
GeoAlchemy2 = "^0.12.5"
psycopg2 = "^2.9.5"
black = "^22.10.0"

[tool.poetry.dev-dependencies]
pytest = "^7.2.0"
black = "^22.10.0"
pylint = "^2.15.5"
pytest-cov = "^4.0.0"
ipython = "^8.6.0"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
