[project]
name = "strava"
version = "0.1.0"
description = "A strava clone service for storing running, hiking and ski routes"
readme = "README.md"
license = "MIT"
requires-python = ">=3.13"
authors = [
  { name = "martinabeleda", email = "martin.abeleda@gmail.com" },
]
dependencies = [
  "uvicorn",
  "fastapi>=0.100.0,<1.0.0",
  "pydantic>=2.0.0,<3.0.0",
  "pydantic-settings",
  "geojson-pydantic",
  "shapely",
  "sqlalchemy>=2.0.0,<3.0.0",
  "geoalchemy2",
  "alembic",
  "psycopg2",
]

[dependency-groups]
dev = [
  "pytest>=8.0.0",
  "pytest-cov>=4.0.0",
  "pre-commit",
  "ruff>=0.6.0",
  "httpx>=0.23.0",
]

[build-system]
requires = ["hatchling>=1.0.0"]
build-backend = "hatchling.build"

[tool.pytest.ini_options]
testpaths = ["tests"]

[tool.ruff]
line-length = 100

[tool.ruff.lint]
extend-select = ["I"]
