"""Added route table

Revision ID: fccefdbcd98e
Revises: 
Create Date: 2022-11-15 04:54:42.317813

"""
from alembic import op
import sqlalchemy as sa
import geoalchemy2


# revision identifiers, used by Alembic.
revision = "fccefdbcd98e"
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "route",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(), nullable=True),
        sa.Column(
            "route",
            geoalchemy2.types.Geometry(
                geometry_type="LINESTRING",
                from_text="ST_GeomFromEWKT",
                name="geometry",
            ),
            nullable=True,
        ),
        sa.Column(
            "activity",
            sa.Enum("RUNNING", "HIKING", "SKIING", name="activity"),
            nullable=True,
        ),
        sa.Column("description", sa.String(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    ) 
    op.create_index(op.f("ix_route_id"), "route", ["id"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_route_id"), table_name="route")
    op.drop_index(
        "idx_route_route", table_name="route", postgresql_using="gist"
    )
    op.drop_table("route")
    # ### end Alembic commands ###
