import os
from uuid import uuid4

from locust import HttpUser, between, task

DEFAULT_API_PREFIX = "/strava/v1"
API_PREFIX = os.getenv("STRAVA_API_PREFIX", DEFAULT_API_PREFIX).rstrip("/")

INTERSECTING_POLYGON = {
    "type": "Polygon",
    "coordinates": [[[-1.0, -1.0], [2.0, -1.0], [2.0, 2.0], [-1.0, 2.0], [-1.0, -1.0]]],
}


class StravaApiUser(HttpUser):
    wait_time = between(1, 3)
    host = os.getenv("LOCUST_HOST", "http://localhost:8080")

    def on_start(self) -> None:
        self.create_route()

    @property
    def routes_path(self) -> str:
        return f"{API_PREFIX}/routes/"

    @property
    def route_search_path(self) -> str:
        return f"{API_PREFIX}/routes/search"

    def create_route_payload(self) -> dict:
        suffix = uuid4().hex[:8]
        return {
            "name": f"load-test-route-{suffix}",
            "route": {
                "type": "LineString",
                "coordinates": [[0.0, 0.0], [1.0, 1.0]],
            },
            "activity": "RUNNING",
            "description": "Generated by locust",
        }

    @task(4)
    def list_routes(self) -> None:
        self.client.get(self.routes_path, name="GET /routes")

    @task(2)
    def list_routes_with_filters(self) -> None:
        self.client.get(
            self.routes_path,
            params={"activity": "RUNNING", "limit": 10},
            name="GET /routes?activity=RUNNING",
        )

    @task(2)
    def create_route(self) -> None:
        with self.client.post(
            self.routes_path,
            json=self.create_route_payload(),
            name="POST /routes",
            catch_response=True,
        ) as response:
            if response.status_code != 200:
                response.failure(f"unexpected status code: {response.status_code}")

    @task(1)
    def intersect_routes(self) -> None:
        self.client.post(
            f"{API_PREFIX}/routes/intersect",
            json=INTERSECTING_POLYGON,
            name="POST /routes/intersect",
        )

    @task(1)
    def conversational_route_search(self) -> None:
        with self.client.post(
            self.route_search_path,
            json={"query": "Running routes in Sydney Australia"},
            name="POST /routes/search",
            catch_response=True,
        ) as response:
            if response.status_code != 200:
                response.failure(f"unexpected status code: {response.status_code}")
