name: "Build and Test"
on: push
jobs:
  test:
    runs-on: ubuntu-latest
    env:
      ENVIRONMENT: ci
      LOGFIRE_TOKEN: ${{ secrets.LOGFIRE_TOKEN }}
    steps:
      - uses: actions/checkout@v4
      - name: Install uv
        uses: astral-sh/setup-uv@v5
        with:
          python-version: "3.13"
      - name: Run test target
        run: make test

  acceptance-test:
    runs-on: ubuntu-latest
    env:
      ENVIRONMENT: ci
      LOGFIRE_TOKEN: ${{ secrets.LOGFIRE_TOKEN }}
    steps:
      - uses: actions/checkout@v4
      - name: Install uv
        uses: astral-sh/setup-uv@v5
        with:
          python-version: "3.13"
      - name: Run acceptance-test target
        run: make acceptance-test

  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Build docker image
        run: make build-docker
