name: "Build and Test"
on: push
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python 3.9
        uses: actions/setup-python@v1
        with:
          python-version: 3.9
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install poetry
          poetry install --no-interaction
      - name: Check formatting
        run: poetry run black --line-length 120 --check 
      - name: Run tests and generate coverage report
        run: poetry run pytest -s --junitxml=./test-report.xml --cov=./ --cov-report=xml .

  build:
    runs-on: ubuntu-latest
    needs: test
    steps:
      - uses: actions/checkout@v2
      - name: Build docker image
        run: docker build -t martinabeleda/strava .
